### PR TITLE
Make fobi wagtail integration work with wagtail 2

### PR DESCRIPTION
**Pull request by just1602**
As far as I test it, it works, but I still have an error about `DJANGO_GTE_1_11` not found even if `django-ǹine` is install. If you have an idea, let me know.

### CODE REVIEW

**Comment by barseghyanartur** [comment]
@just1602:

Thank you!

Where does it exactly complain about ``PYTHON_GTE_1_11``? It's a mistype. It should be ``DJANGO_GTE_1_11``.

**Comment by just1602** [comment]
I have the following error for a couple of tests : `NameError: name 'DJANGO_GTE_1_11' is not defined`.

You're right, it's `DJANGO_GTE_1_11`.

**Comment by barseghyanartur** [comment]
@just1602:

Master is currently development branch (temporarily). Current stable branch is v0.13.x. Nothing should be failing there. I'll merge this into master (shall happen anyway) and manually reflect your changes in the v.0.13.x.

Thank you!

**Comment by just1602** [comment]
Do you have an idea when the changes will be release?

**Comment by barseghyanartur** [comment]
@just1602:

I though I already made a release, but it turns out that not yet. I'll make a release today. Thanks for reminding.

**Comment by just1602** [comment]
Thanks for the backport work. :)

**Comment by barseghyanartur** [comment]
@just1602:

Sorry for delay. I have just released [0.13.7](https://pypi.org/project/django-fobi/0.13.7/).

**Pull request merged**
