### PR TITLE
fobi rich text content plugin based on summernote 

### PR DESCRIPTION
**Pull request by minusf**

### CODE REVIEW

**Comment by barseghyanartur** [comment]
@minusf:

Thank you!

**Comment by minusf** [comment]
i did not update the features section of main documentation yet.
let me know how it works for you.

**Comment by barseghyanartur** [comment]
@minusf:

Some tiny bits of additional work are needed here https://github.com/barseghyanartur/django-fobi/tree/master/src/fobi/contrib/apps/drf_integration/form_elements/content

If you don't feel like doing that, leave it to me.

**Comment by barseghyanartur** [comment]
@minusf:

There's a tiny issue with the plugin. The widget assumes that jQuery has already been loaded, however, it still hasn't (it loads at the end of the page). That's why the way it should be done, for instance, if all configuration files would be declared on the page (for instance in a variable fobiSummernoteConfig, which would hold multiple configurations (in case there are multiple plugins used on the page) and the plugin itself should come with a fobi specific script, which would walk through the configurations on the page and initialize editors one by one. Do you think you could make appropriate changes?

**Comment by minusf** [comment]
yes, this is correct, sorry about that. i forked the fobi bootstrap3 theme (updated to latest bootstrap and jquery).  i also override the summernote config to use the theme provided bootstrap and jquery and i moved the js to the top...

```
{% block extra-head-javascripts %}
{% for js in fobi_theme.get_media_js %}
  <script src="{{ js }}"></script>
{% endfor %}
{% endblock extra-head-javascripts %}
```

i am not sure what the best approach would be here, tbh i am not a fan of multiple versions of the same script. i know that ideally all js should come at end of the page but with widgets requiring all these javascripts this is basically impossible (same with captcha).

**Comment by barseghyanartur** [comment]
@minusf:

Look:

- Fobi collects media files from plugins used and lists them at the bottom, where the scripts are.
- Fobi does include same script twice.

Current situation (doesn't work):

- Each fobi content-richtext plugin adds a piece of javascript which requires jQuery.

Solution (what would work):

- Each fobi content-richtext plugin should append a JSON config to certain variable (shall it be named ``fobiContentRichTextConfig``).
- Fobi content-richtext plugin, shall include a script which would walk through the ``fobiContentRichTextConfig`` and initialize the summernote for every widget.

That's all.

**Comment by minusf** [comment]
summernote already has functionality for this called 'lazy mode'.  in that case all widgets just add themselves to an array and the init function must be called manually later on.  i will look into it.

**Pull request merged**
