### PR TITLE
use DjangoJSONEncoder to handle dates

### PR DESCRIPTION
**Pull request by minusf**
fix the `'datetime' is not JSON serializable` error.

### CODE REVIEW

**Comment by barseghyanartur** [comment]
@minusf:

Thank you!

**Comment by minusf** [comment]
It seems like this PR never made it into a release. Could you please have it in the next release?

**Comment by barseghyanartur** [comment]
Sure. Thanks for pinging.

**Comment by barseghyanartur** [comment]
Done in 0.16.1.

**Comment by minusf** [comment]
thank you!

**Pull request merged**
