### PR TITLE
Made it easier to extend `fobi.integration.processors.IntegrationProcessor`

### PR DESCRIPTION
**Pull request by ababic**
Related to #46.

* Added `get_context_data()`, `get_form_template_name()`, `get_success_page_template_name()` and `get_login_required_template_name()` methods to give developers an 'in' for manipulating those things when rendering
* For all `IntegrationProcessor` views, context dicts are all built using the `get_context_data()` method, that can be overridden to supply additional data to the context
* For all `IntegrationProcessor ` views, the relevant `get_template_*_name` method is used to identify the template to use (templates defined on themes are still used as fallbacks where appropriate)

### CODE REVIEW

**Comment by ababic** [comment]
Hi @barseghyanartur. I've added the above changes as a separate pull for your review. This should make it possible to add the wagtail_integration app in the DRYest way possible.

Forgive me, but I've not been able to figure out how to run tests for this project. Any pointers? `tox` seems to be throwing InvocationErrors at me.

**Comment by ababic** [comment]
Oh. I wasn't expecting that to be merged so quickly... I hadn't had a chance to work out tests just yet.

**Comment by ababic** [comment]
Talking of tests, have you ever tried using the Travis CI github integration? It's very easy to set up. I think all you'd need is a `.travis.yml` file in your project route, and you'd be able to trigger you tox tests to automatically run on every commit (and pull request)

**Comment by barseghyanartur** [comment]
@ababic:

I do use travis for other projects, like this this [one](https://github.com/barseghyanartur/transliterate/blob/master/.travis.yml). I think I tried it once with fobi and it failed on tests and I never got (time to get) bothered with it. But it's all open for improvements. However, I wouldn't want to replace existing tests browser tests with headless versions, as I find visual ones very useful. Instead, I would rather make it configurable (and selectively running for both headless and non-headless testing).

**Comment by ababic** [comment]
I know how you feel :) I only mentioned it as it's saved me many headaches on some projects I've worked on. I never trust anybody's code not to break stuff (especially my own!), so I love the reassurance it gives me.

**Comment by barseghyanartur** [comment]
@ababic:

As of tests, tox works fine for me. I do use a custom Firefox (version 47, since latest version of selenium works fine with it), since selenium is famous of failing on each new Firefox update. I have just added a [section](https://github.com/barseghyanartur/django-fobi#tests) with with some information about it. Thanks for bringing it up.

**Pull request merged**
