### PR TITLE
Non horizontal forms (bootstrap)

### PR DESCRIPTION
**Pull request by minusf**
bootstrap's `form-horizontal` seems to be a bit hardcoded in fobi. i need to use the vanilla bootstrap forms, not the horizontal ones. while the class can be easily overriden, sorting drag and drop will stop working as it's based on form class.

### CODE REVIEW

**Comment by barseghyanartur** [comment]
@minusf:

Your changes do make sense. I have been misusing the "form-horizontal" class. However, I'm not merging it into master. Your changes cover the bootstrap3 theme only (which is definitely the most complete and used theme), while other 3 themes (and correspondent JS code) are not updated. I would like to keep some sort of consistency between the themes for ease of future updates.

Therefore, I consider this a work-in-progress, to be done in the non-form-horizontal branch.

**Comment by barseghyanartur** [comment]
@minusf:

There's [new dedicated issue](https://github.com/barseghyanartur/django-fobi/issues/113) opened.

**Comment by minusf** [comment]
unfortunately i cannot develop and test changes for the other themes, it's too time consuming and i dont use them at all.  and while in principle i agree, except the javascript part i feel these changes are valid for the bootstrap theme and should be merged into master.

also, the current javascript snippet forces all the themes to use bootstrap class name?

**Comment by minusf** [comment]
i also find a bit confusing the arbitrary choices of the theme customisation: in some places context variables are passed in, in others template blocks are abused as variables...

**Comment by barseghyanartur** [comment]
@minusf:

Yep. The ``form-horizontal`` is used as form identifier for other themes and parts of JS are dependant on it.

You don't have to do all the changes. You've done enough already. :) I'll do the rest myself. However, I can't promise it would be done ASAP. What I can tell you, is that your part of code would likely stay intact (as I have merged it into the dedicated branch and it would be merged into the master finally). So, if you could use your fork in the meantime (and merge master changes into that fork from time to time, until it's merged into master). 

Please, don't submit other pull requests based on that fork; use master.

Regarding the arbitrary choices. I might be confusing, yes. I even think it is, BUT it works. :) I even have plans (there's a ticket for it) to extend themes to Bootstrap 4 and Foundation 6 (or even more recent versions of both). I'll likely make some improvements then. But, I can't do it all in my spare time, since I maintain way too many projects already. Big changes like that are implemented faster if (partly) sponsored. 

Finally, I don't think I have said that already, but really appreciate your help. Keep up good work!

**Comment by barseghyanartur** [comment]
@minusf:

Solved in 0.12.13.

**Pull request merged**
